// Google image-search links for the wine names on the Discover card. Tapping a wine's name opens a search for a clean bottle photo of that wine.
// The list comes from the project file wine-photo-links.md (the "photos" link of each of the 200 wines); only the search words are kept here,
// because every link starts the same way. A wine that is not in the list (one added later) gets a search built from its own details.
// Pure: no browser, no network.
const BASE = "https://www.google.com/search?tbm=isch&q=";
// [name as listed (a grape in brackets tells apart wines that share a name), search words]
export const LINKS = [
  ["2021 19 Crimes Red Blend", "19+Crimes+Red+Blend+South+Eastern+Australia+wine+bottle"],
  ["2022 A to Z Wineworks (Pinot Noir)", "A+to+Z+Wineworks+Pinot+Noir+Oregon+wine+bottle"],
  ["2023 Alamos (Chardonnay)", "Alamos+Chardonnay+Mendoza+wine+bottle"],
  ["2022 Alamos (Malbec)", "Alamos+Malbec+Mendoza+wine+bottle"],
  ["2023 Albert Bichot Origines", "Albert+Bichot+Bourgogne+Origines+wine+bottle"],
  ["2023 Apothic White", "Apothic+White+California+wine+bottle"],
  ["2021 Apothic Red", "Apothic+Red+California+wine+bottle"],
  ["2023 Aubert UV-SL Vineyard (Chardonnay)", "Aubert+Chardonnay+Sonoma+Coast+Uv-Sl+Vineyard+wine+bottle"],
  ["NV Barefoot (Pinot Grigio)", "Barefoot+Pinot+Grigio+California+wine+bottle"],
  ["NV Barefoot (Moscato)", "Barefoot+Moscato+California+wine+bottle"],
  ["NV Barefoot (Cabernet Sauvignon)", "Barefoot+Cabernet+Sauvignon+California+wine+bottle"],
  ["2022 Barnett (Merlot)", "Barnett+Merlot+Spring+Mountain+District+wine+bottle"],
  ["2020 Baron Philippe de Rothschild Mouton Cadet", "Baron+Philippe+de+Rothschild+Mouton+Cadet+Bordeaux+wine+bottle"],
  ["2023 Bedrock Bedrock Vineyard Heritage", "Bedrock+Vineyard+Heritage+Sonoma+Valley+wine+bottle"],
  ["2021 Beringer Founders' Estate (Cabernet Sauvignon)", "Beringer+Cabernet+Sauvignon+Founders%27+Estate+California+wine+bottle"],
  ["2023 Bernhard Ott Fass 4 (Grüner Veltliner)", "Bernhard+Ott+Gr%C3%BCner+Veltliner+Nieder%C3%B6sterreich+Fass+4+wine+bottle"],
  ["2023 BiancaVigna Brut", "BiancaVigna+Brut+Conegliano+Valdobbiadene+Prosecco+Superiore+wine+bottle"],
  ["2023 Bodega Catena Zapata Nicasia Vineyard (Malbec)", "Bodega+Catena+Zapata+Malbec+Paraje+Altamira+Nicasia+Vineyard+wine+bottle"],
  ["2022 Bodega Catena Zapata Catena (Malbec)", "Bodega+Catena+Zapata+Malbec+Catena+Mendoza+wine+bottle"],
  ["2022 Bodegas Alto Moncayo Barambán Edición Limitada (Garnacha-Tempranillo)", "Bodegas+Alto+Moncayo+Garnacha-Tempranillo+Campo+de+Borja+Baramb%C3%A1n+Edici%C3%B3n+Limitada+wine+bottle"],
  ["2022 Bodegas Bhilar White Bhilar", "Bodegas+Bhilar+Rioja+White+Bhilar+wine+bottle"],
  ["2021 Bodegas Protos Carroa", "Bodegas+Protos+Ribera+del+Duero+Carroa+wine+bottle"],
  ["2022 Bodegas y Viñedos Artuke Pies Rotos", "Bodegas+y+Vi%C3%B1edos+Artuke+Rioja+Pies+Rotos+wine+bottle"],
  ["2021 Bogle Vineyards Old Vine (Zinfandel)", "Bogle+Vineyards+Zinfandel+Old+Vine+California+wine+bottle"],
  ["2022 Bosquet des Papes", "Bosquet+des+Papes+Ch%C3%A2teauneuf-du-Pape+wine+bottle"],
  ["NV Bota Box (Cabernet Sauvignon)", "Bota+Box+Cabernet+Sauvignon+California+wine+bottle"],
  ["2023 Burn Cottage Moonlight Race (Pinot Noir)", "Burn+Cottage+Pinot+Noir+Central+Otago+Moonlight+Race+wine+bottle"],
  ["2020 Camigliano", "Camigliano+Brunello+di+Montalcino+wine+bottle"],
  ["2021 Campo Viejo (Tempranillo)", "Campo+Viejo+Tempranillo+Rioja+wine+bottle"],
  ["2022 Cantele (Primitivo)", "Cantele+Primitivo+Salento+wine+bottle"],
  ["2023 Cantine Lunae Bosoni Grey Label (Vermentino)", "Cantine+Lunae+Bosoni+Vermentino+Colli+di+Luni-Liguria+Grey+Label+wine+bottle"],
  ["2020 Carpineto Riserva", "Carpineto+Chianti+Classico+Riserva+wine+bottle"],
  ["NV Casal Garcia", "Casal+Garcia+Vinho+Verde+wine+bottle"],
  ["2023 Castello Banfi Principessa Gavia", "Castello+Banfi+Principessa+Gavia+Gavi+wine+bottle"],
  ["2022 Castello Banfi Centine", "Castello+Banfi+Toscana+Centine+wine+bottle"],
  ["2021 Castello di Ama San Lorenzo Gran Selezione", "Castello+di+Ama+Chianti+Classico+San+Lorenzo+Gran+Selezione+wine+bottle"],
  ["2020 Castello di Monsanto San Donato in Poggio Il Poggio Gran Selezione", "Castello+di+Monsanto+Chianti+Classico+San+Donato+in+Poggio+Il+Poggio+Gran+Selezione+wine+bottle"],
  ["2023 Caterwaul (Cabernet Sauvignon)", "Caterwaul+Cabernet+Sauvignon+Napa+Valley+wine+bottle"],
  ["2022 Charles Shaw (Cabernet Sauvignon)", "Charles+Shaw+Cabernet+Sauvignon+California+wine+bottle"],
  ["2022 Château Beau-Séjour Bécot", "Ch%C3%A2teau+Beau-S%C3%A9jour+B%C3%A9cot+St.-Emilion+wine+bottle"],
  ["2024 Château d'Esclans Whispering Angel", "Ch%C3%A2teau+d%27Esclans+Whispering+Angel+C%C3%B4tes+de+Provence+wine+bottle"],
  ["2024 Château d'Estoublon Roseblood Rosé", "Ch%C3%A2teau+d%E2%80%99Estoublon+Coteaux+Varois+en+Provence+Roseblood+Ros%C3%A9+wine+bottle"],
  ["2022 Château de St.-Cosme", "Ch%C3%A2teau+de+St.-Cosme+Gigondas+wine+bottle"],
  ["2022 Château Giscours", "Ch%C3%A2teau+Giscours+Margaux+wine+bottle"],
  ["2022 Château Marquis de Terme", "Ch%C3%A2teau+Marquis+de+Terme+Margaux+wine+bottle"],
  ["2022 Château Smith-Haut-Lafitte White", "Ch%C3%A2teau+Smith-Haut-Lafitte+Pessac-L%C3%A9ognan+White+wine+bottle"],
  ["2024 Chateau Ste. Michelle (Riesling)", "Chateau+Ste.+Michelle+Riesling+Columbia+Valley+wine+bottle"],
  ["2023 Chateau Ste. Michelle (Chardonnay)", "Chateau+Ste.+Michelle+Chardonnay+Columbia+Valley+wine+bottle"],
  ["2022 Château Talbot", "Ch%C3%A2teau+Talbot+St.-Julien+wine+bottle"],
  ["2022 Cheval des Andes", "Cheval+des+Andes+Mendoza+wine+bottle"],
  ["2022 Citra", "Citra+Montepulciano+d%27Abruzzo+wine+bottle"],
  ["2023 Claude Riffault Les Boucauds", "Claude+Riffault+Sancerre+Les+Boucauds+wine+bottle"],
  ["2021 Clos Apalta", "Clos+Apalta+Apalta+wine+bottle"],
  ["2023 Clos Ste.-Magdeleine", "Clos+Ste.-Magdeleine+Cassis+wine+bottle"],
  ["2024 Cloudy Bay (Sauvignon Blanc)", "Cloudy+Bay+Sauvignon+Blanc+Marlborough+wine+bottle"],
  ["2021 Columbia Crest Grand Estates (Cabernet Sauvignon)", "Columbia+Crest+Cabernet+Sauvignon+Grand+Estates+Columbia+Valley+wine+bottle"],
  ["2023 Comando G Rozas de Puerto Real Valle del Tiétar", "Comando+G+Vinos+de+Madrid+Sierra+de+Gredos+Rozas+de+Puerto+Real+Valle+del+Ti%C3%A9tar+wine+bottle"],
  ["2024 Concha y Toro Casillero del Diablo (Sauvignon Blanc)", "Concha+y+Toro+Sauvignon+Blanc+Casillero+del+Diablo+Central+Valley+wine+bottle"],
  ["2022 Concha y Toro Casillero del Diablo (Cabernet Sauvignon)", "Concha+y+Toro+Cabernet+Sauvignon+Casillero+del+Diablo+Central+Valley+wine+bottle"],
  ["2022 Concha y Toro Casillero del Diablo (Carmenère)", "Concha+y+Toro+Carmen%C3%A8re+Casillero+del+Diablo+Central+Valley+wine+bottle"],
  ["2023 Cono Sur Bicicleta (Pinot Noir)", "Cono+Sur+Pinot+Noir+Bicicleta+Central+Valley+wine+bottle"],
  ["2022 Conte Vistarino Costa del Nero (Pinot Nero)", "Conte+Vistarino+Pinot+Nero+dell%E2%80%99Otrep%C3%B2+Pavese+Costa+del+Nero+wine+bottle"],
  ["2023 Cristom Mt. Jefferson Cuvée (Pinot Noir)", "Cristom+Pinot+Noir+Eola-Amity+Hills+Mt.+Jefferson+Cuv%C3%A9e+wine+bottle"],
  ["2023 Cupcake Vineyards (Chardonnay)", "Cupcake+Vineyards+Chardonnay+Central+Coast+wine+bottle"],
  ["2021 Cupcake Vineyards Red Velvet", "Cupcake+Vineyards+Red+Velvet+California+wine+bottle"],
  ["2021 Damilano Cannubi", "Damilano+Barolo+Cannubi+wine+bottle"],
  ["2021 Dark Horse (Cabernet Sauvignon)", "Dark+Horse+Cabernet+Sauvignon+California+wine+bottle"],
  ["2021 Decoy (Cabernet Sauvignon)", "Decoy+Cabernet+Sauvignon+Sonoma+County+wine+bottle"],
  ["2023 Dehlinger Estate (Pinot Noir)", "Dehlinger+Pinot+Noir+Russian+River+Valley+Estate+wine+bottle"],
  ["2024 Diatom (Chardonnay)", "Diatom+Chardonnay+Santa+Barbara+County+wine+bottle"],
  ["2022 Domaine de la Vieille Julienne Les Trois Sources", "Domaine+de+la+Vieille+Julienne+Ch%C3%A2teauneuf-du-Pape+Les+Trois+Sources+wine+bottle"],
  ["2022 Domaine du Closel La Jalousie Château des Vaults", "Domaine+du+Closel+Savenni%C3%A8res+La+Jalousie+Ch%C3%A2teau+des+Vaults+wine+bottle"],
  ["2022 Domaine Laroche Saint Martin", "Domaine+Laroche+Saint+Martin+Chablis+wine+bottle"],
  ["2022 Domaine Michel Magnien", "Domaine+Michel+Magnien+Bourgogne+C%C3%B4te+d%E2%80%99Or+wine+bottle"],
  ["2024 Dr. Loosen Dr. L (Riesling)", "Dr.+Loosen+Riesling+Dr.+L+Mosel+wine+bottle"],
  ["2023 Dr. Loosen Kabinett Erdener Treppchen (Riesling)", "Dr.+Loosen+Riesling+Kabinett+Mosel+Erdener+Treppchen+wine+bottle"],
  ["2023 Dry Creek Dry (Chenin Blanc)", "Dry+Creek+Chenin+Blanc+Clarksburg+Dry+wine+bottle"],
  ["2022 Duckhorn Three Palms Vineyard (Merlot)", "Duckhorn+Merlot+Napa+Valley+Three+Palms+Vineyard+wine+bottle"],
  ["2020 E. Guigal", "E.+Guigal+C%C3%B4tes+du+Rh%C3%B4ne+wine+bottle"],
  ["2024 Ecco Domani (Pinot Grigio)", "Ecco+Domani+Pinot+Grigio+Delle+Venezie+wine+bottle"],
  ["2022 Elderton (Cabernet Sauvignon)", "Elderton+Cabernet+Sauvignon+Barossa+wine+bottle"],
  ["2021 Epoch Veracity", "Epoch+Veracity+Paso+Robles+Willow+Creek+District+wine+bottle"],
  ["2022 Erath (Pinot Noir)", "Erath+Pinot+Noir+Oregon+wine+bottle"],
  ["2021 Etude (Cabernet Sauvignon)", "Etude+Cabernet+Sauvignon+Rutherford+wine+bottle"],
  ["2022 Fairview Goats do Roam Red", "Fairview+Goats+do+Roam+Red+Western+Cape+wine+bottle"],
  ["2021 Famiglia Cotarella Montiano", "Famiglia+Cotarella+Lazio+Montiano+wine+bottle"],
  ["2024 Familia Zuccardi Botánico", "Familia+Zuccardi+Bot%C3%A1nico+Gualtallary+wine+bottle"],
  ["2022 Famille Isabel Ferrando St.-Préfert", "Famille+Isabel+Ferrando+Ch%C3%A2teauneuf-du-Pape+St.-Pr%C3%A9fert+wine+bottle"],
  ["2022 Famille Lieubeau", "Famille+Lieubeau+Muscadet+de+S%C3%A8vre+et+Maine+Clisson+wine+bottle"],
  ["2022 Famille Perrin Réserve", "Famille+Perrin+R%C3%A9serve+C%C3%B4tes+du+Rh%C3%B4ne+wine+bottle"],
  ["2023 Foradori Fontanasanta (Manzoni Bianco)", "Foradori+Manzoni+Bianco+Vigneti+delle+Dolomiti+Fontanasanta+wine+bottle"],
  ["2022 Freemark Abbey Cabernet Bosché (Cabernet Sauvignon)", "Freemark+Abbey+Cabernet+Sauvignon+Rutherford+Cabernet+Bosch%C3%A9+wine+bottle"],
  ["NV Freixenet Cordón Negro Brut", "Freixenet+Cord%C3%B3n+Negro+Brut+Cava+wine+bottle"],
  ["2023 Frequency GSM", "Frequency+Gsm+Santa+Barbara+County+wine+bottle"],
  ["2023 Georges Duboeuf", "Georges+Duboeuf+Beaujolais-Villages+wine+bottle"],
  ["2024 Graci Rosato", "Graci+Etna+Rosato+wine+bottle"],
  ["NV Graham Tawny Port 20 Year Old", "Graham+Tawny+Port+20+Year+Old+Nv+wine+bottle"],
  ["2022 Hartford Family Old Vine (Zinfandel)", "Hartford+Family+Zinfandel+Russian+River+Valley+Old+Vine+wine+bottle"],
  ["2023 Henri Bourgeois Les Baronnes (Sauvignon Blanc)", "Henri+Bourgeois+Sauvignon+Blanc+Les+Baronnes+Sancerre+wine+bottle"],
  ["2021 Hugh Hamilton Black Ops (Shiraz-Saperavi)", "Hugh+Hamilton+Shiraz-Saperavi+South+Australia+Black+Ops+wine+bottle"],
  ["2019 Il Poggione Vigna Paganelli Riserva", "Il+Poggione+Brunello+di+Montalcino+Vigna+Paganelli+Riserva+wine+bottle"],
  ["2024 Indaba (Chenin Blanc)", "Indaba+Chenin+Blanc+Western+Cape+wine+bottle"],
  ["2022 Jean-Louis Chave Sélection White Circa", "Jean-Louis+Chave+S%C3%A9lection+St.-Joseph+White+Circa+wine+bottle"],
  ["2022 Joel Gott 815 (Cabernet Sauvignon)", "Joel+Gott+Cabernet+Sauvignon+815+California+wine+bottle"],
  ["2023 Joseph Drouhin Laforêt (Pinot Noir)", "Joseph+Drouhin+Pinot+Noir+Lafor%C3%AAt+Bourgogne+wine+bottle"],
  ["2023 Josh Cellars (Chardonnay)", "Josh+Cellars+Chardonnay+California+wine+bottle"],
  ["2022 Josh Cellars (Cabernet Sauvignon)", "Josh+Cellars+Cabernet+Sauvignon+California+wine+bottle"],
  ["2022 Josh Cellars (Pinot Noir)", "Josh+Cellars+Pinot+Noir+California+wine+bottle"],
  ["2022 Juan Gil (Monastrell)", "Juan+Gil+Monastrell+Jumilla+wine+bottle"],
  ["2024 Ken Forrester Old Vine Reserve (Chenin Blanc)", "Ken+Forrester+Chenin+Blanc+Stellenbosch+Old+Vine+Reserve+wine+bottle"],
  ["2023 Ken Wright Shea Vineyard (Pinot Noir)", "Ken+Wright+Pinot+Noir+Yamhill-Carlton+Shea+Vineyard+wine+bottle"],
  ["2023 Kendall-Jackson Vintner's Reserve (Chardonnay)", "Kendall-Jackson+Chardonnay+Vintner%27s+Reserve+California+wine+bottle"],
  ["2021 Kendall-Jackson Vintner's Reserve (Cabernet Sauvignon)", "Kendall-Jackson+Cabernet+Sauvignon+Vintner%27s+Reserve+California+wine+bottle"],
  ["2024 Kim Crawford (Sauvignon Blanc)", "Kim+Crawford+Sauvignon+Blanc+Marlborough+wine+bottle"],
  ["2021 Kirkland Signature (Cabernet Sauvignon)", "Kirkland+Signature+Cabernet+Sauvignon+Napa+Valley+wine+bottle"],
  ["NV Korbel Brut", "Korbel+Brut+California+wine+bottle"],
  ["2023 La Crema (Chardonnay)", "La+Crema+Chardonnay+Monterey+wine+bottle"],
  ["2016 La Granja Nuestra Señora de Remelluri Reserva", "La+Granja+Nuestra+Se%C3%B1ora+de+Remelluri+Rioja+Reserva+wine+bottle"],
  ["NV La Marca", "La+Marca+Prosecco+wine+bottle"],
  ["2023 Lamadrid Single Vineyard Reserva (Malbec)", "Lamadrid+Malbec+Agrelo+Single+Vineyard+Reserva+wine+bottle"],
  ["2022 Le Vieux Donjon", "Le+Vieux+Donjon+Ch%C3%A2teauneuf-du-Pape+wine+bottle"],
  ["2023 Lindeman's Bin 65 (Chardonnay)", "Lindeman%27s+Chardonnay+Bin+65+South+Eastern+Australia+wine+bottle"],
  ["2022 Lingua Franca Avni (Pinot Noir)", "Lingua+Franca+Pinot+Noir+Willamette+Valley+Avni+wine+bottle"],
  ["2021 Los Vascos (Cabernet Sauvignon)", "Los+Vascos+Cabernet+Sauvignon+Colchagua+Valley+wine+bottle"],
  ["2022 Louis Jadot Clos des Ursules Héritiers Louis Jadot", "Louis+Jadot+Beaune+Clos+des+Ursules+H%C3%A9ritiers+Louis+Jadot+wine+bottle"],
  ["2022 Louis Jadot", "Louis+Jadot+Pouilly-Fuiss%C3%A9+wine+bottle"],
  ["2021 Louis M. Martini (Cabernet Sauvignon)", "Louis+M.+Martini+Cabernet+Sauvignon+Sonoma+County+wine+bottle"],
  ["2023 Loveblock (Sauvignon Blanc)", "Loveblock+Sauvignon+Blanc+Marlborough+tee+wine+bottle"],
  ["2022 M. Chapoutier Belleruche", "M.+Chapoutier+Belleruche+C%C3%B4tes+du+Rh%C3%B4ne+wine+bottle"],
  ["2022 Marchesi de' Frescobaldi Nipozzano Riserva", "Marchesi+de%E2%80%99+Frescobaldi+Chianti+Rufina+Nipozzano+Riserva+wine+bottle"],
  ["2024 Marisco The Ned (Pinot Gris)", "Marisco+Pinot+Gris+Marlborough+The+Ned+wine+bottle"],
  ["2020 Marqués de Cáceres Crianza", "Marqu%C3%A9s+de+C%C3%A1ceres+Crianza+Rioja+wine+bottle"],
  ["2024 Martín Códax (Albariño)", "Mart%C3%ADn+C%C3%B3dax+Albari%C3%B1o+R%C3%ADas+Baixas+wine+bottle"],
  ["2021 Masi Campofiorin", "Masi+Campofiorin+Rosso+del+Veronese+wine+bottle"],
  ["2024 Massican Annia", "Massican+Annia+California+wine+bottle"],
  ["2023 Masút Eagle Peak Estate Vineyard (Pinot Noir)", "Mas%C3%BAt+Pinot+Noir+Eagle+Peak+Estate+Vineyard+wine+bottle"],
  ["NV Mateus Rosé", "Mateus+Ros%C3%A9+wine+bottle"],
  ["2021 Matteo Ascheri", "Matteo+Ascheri+Barolo+wine+bottle"],
  ["2022 Meiomi (Pinot Noir)", "Meiomi+Pinot+Noir+California+wine+bottle"],
  ["2023 Melville Sandy's Block (Pinot Noir)", "Melville+Pinot+Noir+Sta.+Rita+Hills+Sandy%E2%80%99s+Block+wine+bottle"],
  ["2021 Ménage à Trois Red", "M%C3%A9nage+%C3%A0+Trois+Red+California+wine+bottle"],
  ["2024 Mezzacorona (Pinot Grigio)", "Mezzacorona+Pinot+Grigio+Trentino+wine+bottle"],
  ["NV Mionetto", "Mionetto+Prosecco+wine+bottle"],
  ["NV Moët & Chandon Impérial Brut", "Mo%C3%ABt+%26+Chandon+Imp%C3%A9rial+Brut+Champagne+wine+bottle"],
  ["2022 Newfound Gravels", "Newfound+Gravels+California+wine+bottle"],
  ["NV Nicolas Feuillatte Réserve Exclusive Brut", "Nicolas+Feuillatte+R%C3%A9serve+Exclusive+Brut+Champagne+wine+bottle"],
  ["2024 Oyster Bay (Sauvignon Blanc)", "Oyster+Bay+Sauvignon+Blanc+Marlborough+wine+bottle"],
  ["2023 Oyster Bay (Pinot Noir)", "Oyster+Bay+Pinot+Noir+Marlborough+wine+bottle"],
  ["2022 Patz & Hall (Chardonnay)", "Patz+%26+Hall+Chardonnay+Sonoma+Coast+wine+bottle"],
  ["NV Paula Kornell Brut", "Paula+Kornell+Brut+California+Nv+wine+bottle"],
  ["2021 Penfolds Koonunga Hill (Shiraz-Cabernet Sauvignon)", "Penfolds+Shiraz+Cabernet+Sauvignon+Koonunga+Hill+South+Eastern+Australia+wine+bottle"],
  ["2022 Penner-Ash (Pinot Noir)", "Penner-Ash+Pinot+Noir+Willamette+Valley+wine+bottle"],
  ["2024 Pine Ridge (Chenin Blanc-Viognier)", "Pine+Ridge+Chenin+Blanc-Viognier+American+wine+bottle"],
  ["2023 Platt Vineyard Estate Reserve (Pinot Noir)", "Platt+Vineyard+Pinot+Noir+West+Sonoma+Coast+Estate+Reserve+wine+bottle"],
  ["NV Ployez-Jacquemart Brut Extra Quality", "Ployez-Jacquemart+Brut+Champagne+Extra+Quality+Nv+wine+bottle"],
  ["2022 Primus The Blend", "Primus+The+Blend+Apalta+wine+bottle"],
  ["2021 Produttori del Barbaresco", "Produttori+del+Barbaresco+Barbaresco+wine+bottle"],
  ["2023 Raíces Ibéricas Las Pizarras Fabla #506 (Garnacha-Syrah)", "Ra%C3%ADces+Ib%C3%A9ricas+Garnacha-Syrah+Calatayud+Las+Pizarrras+Fabla+%23506+wine+bottle"],
  ["2023 Ravenswood (Zinfandel)", "Ravenswood+Zinfandel+Dry+Creek+Valley+wine+bottle"],
  ["2021 Ravenswood Vintners Blend (Zinfandel)", "Ravenswood+Zinfandel+Vintners+Blend+California+wine+bottle"],
  ["2022 Ravines Dry (Riesling)", "Ravines+Riesling+Finger+Lakes+Dry+wine+bottle"],
  ["2022 Reynvaan In The Rocks (Syrah)", "Reynvaan+Syrah+Walla+Walla+Valley+In+The+Rocks+wine+bottle"],
  ["2023 Ridge Lytton Springs", "Ridge+Lytton+Springs+Dry+Creek+Valley+wine+bottle"],
  ["2024 Rimapere Single Vineyard (Sauvignon Blanc)", "Rimapere+Sauvignon+Blanc+Marlborough+Single+Vineyard+wine+bottle"],
  ["NV Riunite Lambrusco", "Riunite+Lambrusco+Emilia+wine+bottle"],
  ["2021 Robert Mondavi Private Selection (Cabernet Sauvignon)", "Robert+Mondavi+Private+Selection+Cabernet+Sauvignon+Central+Coast+wine+bottle"],
  ["2023 Rocca di Frassinello Ornello", "Rocca+di+Frassinello+Maremma+Toscana+Ornello+wine+bottle"],
  ["2023 Rodney Strong (Chardonnay)", "Rodney+Strong+Chardonnay+Sonoma+County+wine+bottle"],
  ["2022 Rosemount Estate Diamond Label (Shiraz)", "Rosemount+Estate+Shiraz+Diamond+Label+South+Eastern+Australia+wine+bottle"],
  ["2021 Ruffino Ducale Riserva", "Ruffino+Chianti+Classico+Ducale+Riserva+wine+bottle"],
  ["2021 Ruffino", "Ruffino+Chianti+Classico+wine+bottle"],
  ["2023 Santa Julia (Malbec)", "Santa+Julia+Malbec+Mendoza+wine+bottle"],
  ["2024 Santa Margherita (Pinot Grigio)", "Santa+Margherita+Pinot+Grigio+Valdadige+wine+bottle"],
  ["2022 Santa Rita 120 (Cabernet Sauvignon)", "Santa+Rita+Cabernet+Sauvignon+120+Central+Valley+wine+bottle"],
  ["2024 Saracco", "Saracco+Moscato+d%27Asti+wine+bottle"],
  ["2024 Schmitt Söhne Relax (Riesling)", "Schmitt+S%C3%B6hne+Riesling+Relax+Mosel+wine+bottle"],
  ["NV Segura Viudas Brut Reserva", "Segura+Viudas+Brut+Reserva+Cava+wine+bottle"],
  ["2022 Sleight of Hand The Spellbinder", "Sleight+of+Hand+The+Spellbinder+Columbia+Valley+wine+bottle"],
  ["2023 Stoller Estate (Pinot Noir)", "Stoller+Pinot+Noir+Dundee+Hills+Estate+wine+bottle"],
  ["NV Sutter Home (Zinfandel)", "Sutter+Home+Zinfandel+California+wine+bottle"],
  ["2022 Symington Family Altano", "Symington+Family+Douro+Altano+wine+bottle"],
  ["NV Taittinger La Française Brut", "Taittinger+La+Fran%C3%A7aise+Brut+Champagne+wine+bottle"],
  ["2024 Te Pa (Sauvignon Blanc)", "Te+Pa+Sauvignon+Blanc+Marlborough+wine+bottle"],
  ["2018 Tenute Capaldo Gulielmus Riserva", "Tenute+Capaldo+Taurasi+Gulielmus+Riserva+wine+bottle"],
  ["2022 The Prisoner Wine Company The Prisoner Red Blend", "The+Prisoner+Wine+Company+The+Prisoner+Red+Blend+Napa+Valley+wine+bottle"],
  ["2023 Trapiche (Malbec)", "Trapiche+Malbec+Mendoza+wine+bottle"],
  ["2021 Venus La Universal Dido La Universal", "Venus+La+Universal+Montsant+Dido+La+Universal+wine+bottle"],
  ["NV Veuve Clicquot Yellow Label Brut", "Veuve+Clicquot+Yellow+Label+Brut+Champagne+wine+bottle"],
  ["2024 Villa Maria Private Bin (Sauvignon Blanc)", "Villa+Maria+Sauvignon+Blanc+Private+Bin+Marlborough+wine+bottle"],
  ["2022 Viña Tarapacá Etiqueta Negra Gran Reserva (Cabernet Sauvignon)", "Vi%C3%B1a+Tarapac%C3%A1+Cabernet+Sauvignon+Maipo+Valley+Etiqueta+Negra+Gran+Reserva+wine+bottle"],
  ["2019 Viticcio Riserva", "Viticcio+Chianti+Classico+Riserva+wine+bottle"],
  ["2023 Wayfarer Wayfarer Vineyard The Estate (Pinot Noir)", "Wayfarer+Pinot+Noir+Fort+Ross-Seaview+Wayfarer+Vineyard+The+Estate+wine+bottle"],
  ["2023 Williams Selyem Eastside Road Neighbors (Pinot Noir)", "Williams+Selyem+Pinot+Noir+Russian+River+Valley+Eastside+Road+Neighbors+wine+bottle"],
  ["2021 Wolf Blass Yellow Label (Cabernet Sauvignon)", "Wolf+Blass+Cabernet+Sauvignon+Yellow+Label+South+Australia+wine+bottle"],
  ["2023 Woodbridge by Robert Mondavi (Chardonnay)", "Woodbridge+by+Robert+Mondavi+Chardonnay+California+wine+bottle"],
  ["2022 Woodbridge by Robert Mondavi (Cabernet Sauvignon)", "Woodbridge+by+Robert+Mondavi+Cabernet+Sauvignon+California+wine+bottle"],
  ["2023 Yellow Tail (Chardonnay)", "Yellow+Tail+Chardonnay+South+Eastern+Australia+wine+bottle"],
  ["2022 Yellow Tail (Shiraz)", "Yellow+Tail+Shiraz+South+Eastern+Australia+wine+bottle"],
  ["2021 Zenato Ripassa", "Zenato+Ripassa+Valpolicella+Ripasso+wine+bottle"],
  ["NV Zonin", "Zonin+Prosecco+wine+bottle"],
];

const fold = (s) => String(s == null ? "" : s).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
// "2022 Alamos (Malbec)" -> the name without the grape, and the grape.
const parts = (name) => { const m = /^(.*?)\s*\(([^)]*)\)\s*$/.exec(name); return m ? { base: m[1], grape: m[2] } : { base: name, grape: "" }; };
const INDEX = new Map();
LINKS.forEach(([name, q]) => { const p = parts(name), k = fold(p.base); if (!INDEX.has(k)) INDEX.set(k, []); INDEX.get(k).push({ grape: fold(p.grape), q }); });
const plus = (words) => encodeURIComponent(words).replace(/%20/g, "+");

// card: a catalog card. Its catalogForm (the catalog's own details, before the player's private changes) is used when there is one,
// so a wine keeps its link even if the player changed its details for themselves.
export function imageSearchUrl(card) {
  const f = (card && card.catalogForm) || {};
  const producer = f.producer != null ? f.producer : card.producer, cuvee = f.wine_name != null ? f.wine_name : card.cuvee, vintage = f.vintage != null ? f.vintage : card.vintage;
  const key = fold([vintage, producer, cuvee].filter(Boolean).join(" "));
  const found = INDEX.get(key);
  if (found && found.length) {
    let hit = found[0];
    if (found.length > 1) {
      const g = fold(f.grape || card.grape || (card.grapes && card.grapes[0]) || (card.ruleGrapes && card.ruleGrapes[0]) || "");
      hit = found.find((x) => x.grape && x.grape === g) || found.find((x) => x.grape && g && (g.startsWith(x.grape) || x.grape.startsWith(g))) || found[0];
    }
    return BASE + hit.q;
  }
  const grape = (card.grapes && card.grapes[0]) || (card.ruleGrapes && card.ruleGrapes[0]) || "";
  return BASE + plus([card.producer, card.cuvee, grape, card.appellation || card.region, "wine bottle"].filter(Boolean).join(" "));
}
